version: 2
jobs:
  build:
    working_directory: /root/encrypted-config-value
    environment:
      TESTS_DIR: /tmp/tests
      TERM: dumb
    docker:
      - image: nmiyake/java:alpine-oracle-jdk-8-t3
        cmd: ["/bin/bash"]
    steps:
      - type: checkout
      - type: cache-restore
        key: gradle-{{ checksum "/root/encrypted-config-value/gradle/wrapper/gradle-wrapper.properties" }}-v2
      - type: shell
        name: "Resolve Gradle configurations"
        command: ./gradlew resolveConfigurations
      - type: cache-save
        key: gradle-{{ checksum "/root/encrypted-config-value/gradle/wrapper/gradle-wrapper.properties" }}-v2
        paths:
          - /root/.gradle
      - type: shell
        name: "Run checks"
        command: ./gradlew check
      - type: test-results-store
        path: /tmp/tests
      - type: deploy
        name: "Publish on release tags"
        command: |
          set -eu
          TAG=$(git describe --tags)
          if [[ $TAG =~ ^[0-9]+(\.[0-9]+)+$ ]]; then
            ./gradlew -i bintrayUpload
          fi
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            # run on all branches and tags
            tags:
              only: /.*/
