buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks-settings:0.70.0'
    }
}
apply plugin: 'com.palantir.jdks.settings'
rootProject.name = 'encrypted-config-value-root'

include 'encrypted-config-value'
include 'encrypted-config-value-module'
