com.fasterxml.jackson.*:* = 2.19.2
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.9.0
com.google.guava:guava = 33.5.0-jre
com.palantir.safe-logging:* = 3.9.0
net.jqwik:* = 1.9.3
org.assertj:assertj-core = 3.27.6
org.immutables:* = 2.11.4
org.junit.jupiter:* = 6.0.0
org.junit.platform:* = 6.0.0
org.mockito:* = 5.20.0
org.objenesis:objenesis = 3.4
