com.fasterxml.jackson.*:* = 2.21.4
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.9.0
com.google.guava:guava = 33.6.0-jre
com.palantir.safe-logging:* = 3.17.0
org.quicktheories:quicktheories = 0.26
org.assertj:assertj-core = 3.27.7
org.immutables:* = 2.12.2
org.junit.jupiter:* = 6.1.1
org.junit.platform:* = 6.1.1
org.mockito:* = 5.23.0
org.objenesis:objenesis = 3.5
