com.fasterxml.jackson.*:* = 2.20.1
com.fasterxml.jackson.core:jackson-annotations = 2.20
com.google.code.findbugs:jsr305 = 3.0.2
com.google.errorprone:error_prone_annotations = 2.9.0
com.google.guava:guava = 33.5.0-jre
com.palantir.safe-logging:* = 3.11.0
net.jqwik:* = 1.9.3
org.assertj:assertj-core = 3.27.7
org.immutables:* = 2.12.1
org.junit.jupiter:* = 6.0.2
org.junit.platform:* = 6.0.2
org.mockito:* = 5.21.0
org.objenesis:objenesis = 3.5
